# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Alex Papaioannou # Your name.
email: a.papaioannou@columbia.edu # Your email

# Use consideration when using these, publicly available contact information
# and place of residence is not something you might want to have.
tagline: Personal cover page for this test user. # Appears on the sidebar bellow your name.
address: 424 West 4th Street, 10022 New York, United States # Your address
phone: 917-435-87 # Your phone number
dob: 05.26.1992 # Your date of birth
image: https://ibb.co/rGR0Lzc/350x350
title: Data Scientist # Your title eg. Writer, programmer, welder, etc.
github_username:  apapaioannou92 # Your github username
linkedin_url: https://www.linkedin.com/in/apapaio/ # Your linkedin public url
twitter_handle: alexpap2018 # Your twitter handle

abstract: > # Here you should write a brief summary about yourself.
Currently my work focuses on corporate workflow transformation and optimization using Process Engineering, Project/Program Management and Lean/Six Sigma/Agile Management principles. 

On the side, I am working as a freelancer on Data Science models that aim to enhance the efficiency of corporations and give them insights in order to formulate better decision making strategies.

Currently, I am happy to work as an internal Consultant, and Program Manager for Nomura Securities.

Regarding my education, I am a graduate of the program M.S. candidate in Management Science & Engineering of Columbia’s  Business School and Engineering School (2019). Lastly, I hold as well a MEng in Civil and Environmental Engineering (2017). 

Favorite programming languages Python, R, SQL, Matlab, C/C++, Fortran 90, Java. 

If you need any further information, please feel free to contact me. Thank you for your time! 
Email address a.papaioannou@columbia.edu

description: > # Description for site meta, used by search engines.
  Personal cover page for this test user.
theme: theme-ocean-orange # Color theme for the site.

# Localization
projects: Personal projects
skills: Skills
languages: Language
hobbies: Hobbies
experience: Experience
education: Education
email_text: Email
phone_text: Phone
dob_text: Date of birth
address_text: Address

baseurl: ""

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
