# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

baseurl: "https://alex-papaioannou.github.io"
# baseurl: "/home"
# root: home/
# url: ""
# permalink: "/blog/:title/"

# Site settings
name: Alex Papaioannou # Your name.
email: a.papaioannou@columbia.edu # Your email

# Use consideration when using these, publicly available contact information
# and place of residence is not something you might want to have.
tagline: Personal cover page for job description, skills, personal projects, education etc. # Appears on the sidebar bellow your name.
address: 424 West 47th Street, 10036 New York, United States # Your address
phone: 917-435-8702 # Your phone number
dob: 05.26.1992 # Your date of birth
image: assets/images/AP_professional_photo_squared.jpg

title: Data Scientist # Your title eg. Writer, programmer, welder, etc.
github_username:  alex-papaioannou # Your github username
linkedin_url: https://www.linkedin.com/in/apapaio/ # Your linkedin public url
twitter_handle: alexpap2018 # Your twitter handle

abstract: > # Here you should write a brief summary about yourself.
#  Currently my work focuses on corporate workflow transformation and optimization using Process Engineering, Project/Program Management and Lean/Six Sigma/Agile Management principles. 
  
#  On the side, I am working as a freelancer on Data Science models that aim to enhance the efficiency of corporations and give them insights in order to formulate better decision making strategies.
  
#  Currently, I am happy to work as an internal Consultant, and Program Manager for Nomura Securities.
  
#  Regarding my education, I am a graduate of the program M.S. candidate in Management Science & Engineering of Columbia’s  Business School and Engineering School (2019). Lastly, I hold as well a MEng in Civil and Environmental Engineering (2017). 

#  At Goldman Sachs I have been developing automated data pipelines and production scripts, leveraging software engineering and data science principles, in order to accomplish risk mitigation, make trading systems more efficient, and reduce the need of manual human intervention during the trade life cycle. 

#  I hold a M.S. Operations Research from Columbia University (2019) and a B.S. in Applied & Pure Math from Indiana University.

#  If you need any further information, please feel free to contact me by email at a.papaioannou@columbia.edu

#core characteristics:
#-meticulous and detail/exception oriented
#-professional experience in 2 fast paced IBs+fintech startup
#-hands-on experience in finance (both front office and middle office functions), project management, data science, DevOps, systems, machine learning, time series analysis, PROD automation using Python, Gitlab, AWS, Kafka, Spark, Docker, Kubernetes, SQL
#-bachelors and masters degrees in math and engineering and 4+ years of research in engineering and financial mathematics
#-professionally mature, adaptable and able to change priorities quickly and work on multiple projects concurrently when roadblocks/dependencies come up

description: > # Description for site meta, used by search engines.
  #Personal cover page for this test user.
# theme: jekyll-theme-hydejack
# remote_theme: theme-default-blue # Color theme for the site.
theme: minima #theme-default-blue # Color theme for the site.
# remote_theme: theme-default-blue #ngzhio/jekyll-theme-hamilton
# Localization
projects: Personal projects
skills: Skills
languages: Language
hobbies: Hobbies
experience: Experience
education: Education
email_text: Email
phone_text: Phone
dob_text: Date of birth
address_text: Address

# <link rel="stylesheet" href="{{ "css/main.css, " | prepend: site.baseurl }}">

# <link rel="stylesheet" href="{{ site.baseurl }}home/css/main.css">
# <link rel="stylesheet" href="/css/main.css">
# <script src="{{ site.baseurl }}/js/scripts.js"></script>
# <img src="{{ site.baseurl }}/path/to/img/toto.jpg">
# <a href="{{ site.baseurl }}/linkto/">Link</a>

# Build settings
markdown: kramdown

plugins:
  - jekyll-image-size
  #   - jekyll-remote-theme

sass:
    sass_dir: _sass
# sass:
#     load_paths:
#         - home/_sass
#         - home/css



# abstract: > # Here you should write a brief summary about yourself.
#   Currently my work focuses on corporate workflow transformation and optimization using Process Engineering, Project/Program Management and Lean/Six Sigma/Agile Management principles. 
  
#   On the side, I am working as a freelancer on Data Science models that aim to enhance the efficiency of corporations and give them insights in order to formulate better decision making strategies.
  
#   Currently, I am happy to work as an internal Consultant, and Program Manager for Nomura Securities.
  
#   Regarding my education, I am a graduate of the program M.S. candidate in Management Science & Engineering of Columbia’s  Business School and Engineering School (2019). Lastly, I hold as well a MEng in Civil and Environmental Engineering (2017). 

# description: > # Description for site meta, used by search engines.
#   #Personal cover page for this test user.
# theme: theme-default-blue # Color theme for the site.

# # Localization
# projects: Personal projects
# skills: Skills
# languages: Language
# hobbies: Hobbies
# experience: Experience
# education: Education
# email_text: Email
# phone_text: Phone
# dob_text: Date of birth
# address_text: Address

# baseurl: ""

# # Build settings
# markdown: kramdown

# plugins:
#   - jekyll-image-size
  
# sass:
#     sass_dir: _sass
